
build:
	javac -classpath lib/commons-logging-1.1.1.jar:lib/commons-lang-2.4.jar:lib/commons-codec-1.3.jar:lib/commons-io-1.4.jar:lib/junit-4.5.jar:lib/ical4j-1.0-rc2.jar:./ Worktime.java

run:
	java -classpath lib/commons-logging-1.1.1.jar:lib/commons-lang-2.4.jar:lib/commons-codec-1.3.jar:lib/commons-io-1.4.jar:lib/junit-4.5.jar:lib/ical4j-1.0-rc2.jar:./ Worktime 20141201T000000 42 mschubert -Xms32m -Xmx1024m

